### ISSUE TITLE
Small error in train script

### ISSUE THREAD

**Issue by attashe** [PixArt-alpha/PixArt-sigma#36]
Launched train script with command:
`python3 train_scripts/train.py           configs/pixart_sigma_config/PixArt_sigma_xl2_img1024_internalms.py           --load-from pretrained/PixArt-Sigma-XL-2-1024-MS.pth`

Got error:

```
Traceback (most recent call last):
  File "/home/ya_mihailov/Github/PixArt-sigma/train_scripts/train.py", line 481, in <module>
    train()
  File "/home/ya_mihailov/Github/PixArt-sigma/train_scripts/train.py", line 196, in train
    f"epoch_eta:{eta_epoch}, time_all:{t:.3f}, time_data:{t_d:.3f}, lr:{lr:.3e}, s:({model.module.h}, {model.module.w}), "
  File "/home/ya_mihailov/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'PixArtMS' object has no attribute 'module'
```
Removed all `model.module*` logs and script is working now

**Comment by lawrence-cj** [comment]
Seems you are not using DDP for training.

**Comment by lawrence-cj** [comment]
Fixed
