### ISSUE TITLE
running the dmd demo raise error

### ISSUE THREAD

**Issue by RyanHuangNLP** [PixArt-alpha/PixArt-sigma#39]
DEMO_PORT=12345 python app/app_pixart_dmd.py, raise the following error:
```
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  2.52it/s]
Loading pipeline components...:  50%|█████████████████████████████████                                 | 2/4 [00:00<00:00,  2.01it/s]
Traceback (most recent call last):
  File "PixArt-sigma/app/app_pixart_dmd.py", line 126, in <module>
    pipe = PixArtAlphaPipeline.from_pretrained(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 877, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/diffusers/pipelines/pipeline_loading_utils.py", line 699, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2044, in _from_pretrained
    raise ValueError(
ValueError: Non-consecutive added token '<pad>' found. Should have index 32100 but has index 0 in saved vocabulary.
```

**Comment by lawrence-cj** [comment]
Update your `transformers`.

**Comment by trouble-maker007** [comment]
@lawrence-cj sorry about that I forget to close the issue, I fix it with update the transformers version already
